name: TBI_env
dependencies:
  - python=3.10
  - pip
  - pip:
      - attrs==25.3.0
      - cartopy==0.25.0
      - cdsapi==0.7.7
      - certifi==2025.8.3
      - cf-xarray==0.10.6
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2025.9.1
      - ecmwf-datastores-client==0.4.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.0
      - locket==1.0.0
      - matplotlib==3.10.6
      - multiurl==0.3.7
      - netcdf4==1.7.2
      - numba==0.62.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - partd==1.4.2
      - patsy==1.0.1
      - pillow==11.3.0
      - psutil==7.1.0
      - pyparsing==3.2.5
      - pyproj==3.7.1
      - pyshp==2.3.1
      - pyspharm==1.0.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - shapely==2.1.2
      - six==1.17.0
      - sparse==0.17.0
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tigramite==5.2.8.2
      - toolz==1.0.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wheel==0.45.1
      - windspharm==2.0.0
      - xarray==2025.6.1
      - xesmf==0.8.10
      - zipp==3.23.0
# Note: compiling pyspharm (windspharm) requires gfortran; export FFLAGS/FCFLAGS="-fallow-argument-mismatch -std=legacy" during installation on GCC 10+ systems.
